const fs = require("fs/promises");
const path = require("path");
const config = require("./config");
const { findMarkdownFiles } = require("./files");
const { parseFrontmatter, extractTitle } = require("./frontmatter");
const { markdownToHtml } = require("./markdown");
const { buildNavTree, buildNavHtml } = require("./nav");
const { templateHtml } = require("./template");
const { writeAssets } = require("./assets");
const { toPosixPath, relativeLink } = require("./utils");

async function main() {
  let siteTitle = config.siteTitle;
  let footerText = "";
  let tempOutputDir;
  try {
    try {
      const metaRaw = await fs.readFile(
        path.join(config.rootDir, "meta.json"),
        "utf8"
      );
      const meta = JSON.parse(metaRaw);
      const context = Array.isArray(meta.context) ? meta.context[0] : null;
      if (context && typeof context === "object") {
        if (typeof context.name === "string" && context.name.trim()) {
          siteTitle = context.name.trim();
        }
        if (typeof context.footer === "string" && context.footer.trim()) {
          footerText = context.footer.trim();
        } else if (typeof context.footer_html === "string") {
          footerText = context.footer_html.replace(/<[^>]*>/g, " ").trim();
        }
      }
    } catch (error) {
      if (error.code !== "ENOENT") {
        throw error;
      }
    }

    let markdownFiles = [];
    try {
      markdownFiles = await findMarkdownFiles(config.contentDir);
    } catch (error) {
      console.error("Failed to read content directory:", error.message);
      return;
    }

    const fileIndex = new Map();
    for (const filePath of markdownFiles) {
      const raw = await fs.readFile(filePath, "utf8");
      const { frontmatter, body } = parseFrontmatter(raw);
      const relPath = toPosixPath(
        path.relative(config.contentDir, filePath)
      ).replace(/\.md$/i, "");
      const slugLower = relPath.toLowerCase();
      const title = extractTitle(body, frontmatter, filePath);
      const outPath = path.join(config.outputDir, relPath + ".html");
      const entry = {
        absPath: filePath,
        relPathNoExt: relPath,
        slugLower,
        title,
        frontmatter,
        body,
        outPath,
      };

      const existingEntry = fileIndex.get(slugLower);
      if (existingEntry) {
        throw new Error(
          `Duplicate page slug "${slugLower}" generated by ` +
            `"${existingEntry.absPath}" and "${filePath}". ` +
            "Rename one of the files so their output paths differ by more than case."
        );
      }

      fileIndex.set(slugLower, entry);
    }

    const navTree = buildNavTree(fileIndex);
    tempOutputDir = await fs.mkdtemp(
      path.join(config.rootDir, `${path.basename(config.outputDir)}-tmp-`)
    );
    const tempAssetsDir = path.join(tempOutputDir, "assets");

    for (const file of fileIndex.values()) {
      const tempOutPath = path.join(
        tempOutputDir,
        path.relative(config.outputDir, file.outPath)
      );
      const styleHref = relativeLink(
        tempOutPath,
        path.join(tempAssetsDir, "style.css")
      );
      const navHtml = buildNavHtml(navTree, file, fileIndex);
      const contentHtml = markdownToHtml(file.body);

      const pageHtml = templateHtml({
        title: file.title,
        nav: navHtml,
        content: contentHtml,
        backlinks: null,
        styleHref,
        siteTitle,
        footerText,
      });

      await fs.mkdir(path.dirname(tempOutPath), { recursive: true });
      await fs.writeFile(tempOutPath, pageHtml, "utf8");
    }

    await writeAssets(tempOutputDir);
    await fs.rm(config.outputDir, { recursive: true, force: true });
    await fs.rename(tempOutputDir, config.outputDir);
    tempOutputDir = null;

    console.log(`Generated ${fileIndex.size} page(s).`);
  } finally {
    if (tempOutputDir) {
      await fs.rm(tempOutputDir, { recursive: true, force: true });
    }
  }
}

module.exports = {
  main,
};
