const fs = require("fs/promises");
const path = require("path");
const config = require("./config");
const { findMarkdownFiles } = require("./files");
const { parseFrontmatter, extractTitle } = require("./frontmatter");
const { markdownToHtml } = require("./markdown");
const { buildNavTree, buildNavHtml } = require("./nav");
const { templateHtml } = require("./template");
const { writeAssets } = require("./assets");
const { escapeHtml, toPosixPath, relativeLink } = require("./utils");

function createIndexEntry(config, siteTitle) {
  return {
    absPath: null,
    relPathNoExt: config.indexName,
    slugLower: config.indexName.toLowerCase(),
    title: "Index",
    frontmatter: {},
    body: "",
    outPath: path.join(config.outputDir, `${config.indexName}.html`),
    generated: true,
  };
}

function buildIndexDirectoryHtml(currentFile, fileIndex) {
  const posts = Array.from(fileIndex.values())
    .filter((file) => file.slugLower !== config.indexName.toLowerCase())
    .sort((a, b) => a.relPathNoExt.localeCompare(b.relPathNoExt));

  if (!posts.length) {
    return '<section class="post-directory"><h2>Posts</h2><p>No posts yet.</p></section>';
  }

  const root = { type: "dir", name: "", children: [] };

  const getOrCreateDir = (parent, name) => {
    let node = parent.children.find(
      (child) => child.type === "dir" && child.name === name
    );
    if (!node) {
      node = { type: "dir", name, children: [] };
      parent.children.push(node);
    }
    return node;
  };

  for (const file of posts) {
    const segments = file.relPathNoExt.split("/");
    let current = root;
    for (let index = 0; index < segments.length; index += 1) {
      const segment = segments[index];
      const isLast = index === segments.length - 1;
      if (isLast) {
        current.children.push({ type: "file", name: segment, file });
      } else {
        current = getOrCreateDir(current, segment);
      }
    }
  }

  const renderChildren = (children) => {
    children.sort((a, b) => {
      if (a.type !== b.type) {
        return a.type === "dir" ? -1 : 1;
      }
      return a.name.localeCompare(b.name);
    });

    const items = children
      .map((child) => {
        if (child.type === "dir") {
          return (
            `<li><span class="post-dir">${escapeHtml(child.name)}</span>` +
            `${renderChildren(child.children)}</li>`
          );
        }

        const href = relativeLink(currentFile.outPath, child.file.outPath);
        return `<li><a href="${href}">${escapeHtml(child.file.title)}</a></li>`;
      })
      .join("");

    return `<ul>${items}</ul>`;
  };

  return `<section class="post-directory"><h2>Posts</h2>${renderChildren(
    root.children
  )}</section>`;
}

async function main() {
  let siteTitle = config.siteTitle;
  let footerText = "";
  let tempOutputDir;
  try {
    try {
      const metaRaw = await fs.readFile(
        path.join(config.rootDir, "meta.json"),
        "utf8"
      );
      const meta = JSON.parse(metaRaw);
      const context = Array.isArray(meta.context) ? meta.context[0] : null;
      if (context && typeof context === "object") {
        if (typeof context.name === "string" && context.name.trim()) {
          siteTitle = context.name.trim();
        }
        if (typeof context.footer === "string" && context.footer.trim()) {
          footerText = context.footer.trim();
        } else if (typeof context.footer_html === "string") {
          footerText = context.footer_html.replace(/<[^>]*>/g, " ").trim();
        }
      }
    } catch (error) {
      if (error.code !== "ENOENT") {
        throw error;
      }
    }

    let markdownFiles = [];
    try {
      markdownFiles = await findMarkdownFiles(config.contentDir);
    } catch (error) {
      console.error("Failed to read content directory:", error.message);
      return;
    }

    const fileIndex = new Map();
    for (const filePath of markdownFiles) {
      const raw = await fs.readFile(filePath, "utf8");
      const { frontmatter, body } = parseFrontmatter(raw);
      const relPath = toPosixPath(
        path.relative(config.contentDir, filePath)
      ).replace(/\.md$/i, "");
      const slugLower = relPath.toLowerCase();
      const title = extractTitle(body, frontmatter, filePath);
      const outPath = path.join(config.outputDir, relPath + ".html");
      const entry = {
        absPath: filePath,
        relPathNoExt: relPath,
        slugLower,
        title,
        frontmatter,
        body,
        outPath,
      };

      const existingEntry = fileIndex.get(slugLower);
      if (existingEntry) {
        throw new Error(
          `Duplicate page slug "${slugLower}" generated by ` +
            `"${existingEntry.absPath}" and "${filePath}". ` +
            "Rename one of the files so their output paths differ by more than case."
        );
      }

      fileIndex.set(slugLower, entry);
    }

    const indexSlug = config.indexName.toLowerCase();
    if (!fileIndex.has(indexSlug)) {
      fileIndex.set(indexSlug, createIndexEntry(config, siteTitle));
    }

    const navTree = buildNavTree(fileIndex);
    tempOutputDir = await fs.mkdtemp(
      path.join(config.rootDir, `${path.basename(config.outputDir)}-tmp-`)
    );
    const tempAssetsDir = path.join(tempOutputDir, "assets");

    for (const file of fileIndex.values()) {
      const tempOutPath = path.join(
        tempOutputDir,
        path.relative(config.outputDir, file.outPath)
      );
      const styleHref = relativeLink(
        tempOutPath,
        path.join(tempAssetsDir, "style.css")
      );
      const navHtml =
        file.slugLower === indexSlug
          ? ""
          : buildNavHtml(navTree, file, fileIndex);
      let contentHtml = markdownToHtml(file.body);
      if (file.slugLower === indexSlug) {
        contentHtml = `${contentHtml}\n${buildIndexDirectoryHtml(file, fileIndex)}`;
      }

      const pageHtml = templateHtml({
        title: file.title,
        nav: navHtml,
        content: contentHtml,
        backlinks: null,
        styleHref,
        siteTitle,
        footerText,
      });

      await fs.mkdir(path.dirname(tempOutPath), { recursive: true });
      await fs.writeFile(tempOutPath, pageHtml, "utf8");
    }

    await writeAssets(tempOutputDir);
    await fs.rm(config.outputDir, { recursive: true, force: true });
    await fs.rename(tempOutputDir, config.outputDir);
    tempOutputDir = null;

    console.log(`Generated ${fileIndex.size} page(s).`);
  } finally {
    if (tempOutputDir) {
      await fs.rm(tempOutputDir, { recursive: true, force: true });
    }
  }
}

module.exports = {
  main,
};
